openapi: 3.1.0

info:
  title: GPB IT Factory Mini-Bank Middle Service API
  version: 0.2.1

servers:
  - url: http://localhost:8081/api

paths:
  /v1/clients:
    post:
      operationId: createNewClient
      summary: Создать нового клиента
      deprecated: true
      tags: [ clients ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClientRequest'
      responses:
        200:
          description: Клиент создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateClientResponse'
        default:
          description: Непредвиденная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v2/clients:
    post:
      operationId: createNewClientV2
      summary: Создать нового клиента
      tags: [ clients ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClientRequestV2'
      responses:
        200:
          description: Клиент создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateClientResponse'
        default:
          description: Непредвиденная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/clients/{telegramId}:
    get:
      operationId: getClient
      summary: Получить данные клиента
      tags: [ clients ]
      parameters:
        - $ref: '#/components/parameters/telegramId'
      responses:
        200:
          description: Данные клиента
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        default:
          description: Непредвиденная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/clients/{telegramId}/accounts:
    post:
      operationId: createClientAccount
      summary: Открыть новый счёт для клиента
      tags: [ accounts ]
      parameters:
        - $ref: '#/components/parameters/telegramId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClientAccountRequest'
      responses:
        201:
          description: Счёт успешно открыт
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateClientAccountResponse'
        422:
          description: В запросе содержится недопустимый контент
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Непредвиденная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/accounts:
    get:
      operationId: getAvailableAccounts
      summary: Получить счета, доступные для открытия
      tags: [ accounts ]
      responses:
        200:
          description: Список счетов доступных для открытия
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountResponse'
        default:
          description: Непредвиденная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateClientRequest:
      type: object
      description: Запрос на создание нового клиента
      properties:
        telegramUserId:
          description: Идентификатор пользователя в Telegram
          type: integer
          format: int64
          examples:
            - 348741706
    CreateClientRequestV2:
      type: object
      description: Запрос на создание нового клиента
      properties:
        telegramUserId:
          description: Идентификатор пользователя в Telegram
          type: integer
          format: int64
          examples:
            - 348741706
        telegramUserName:
          description: Username пользователя в Telegram
          type: string
          examples:
            - admin
      required:
        - telegramUserId
        - telegramUserName
    CreateClientAccountRequest:
      type: object
      description: Запрос на создание нового счёта
      properties:
        accountName:
          type: string
          examples:
            - Акционный
      required:
        - accountName
    CreateClientResponse:
      type: object
      description: Информация о успешной регистрации клиента
      properties:
        message:
          type: string
          examples:
            - Клиент успешно зарегистрирован
    CreateClientAccountResponse:
      type: object
      description: Информация об успешном открытии счёта для клиента
      properties:
        message:
          type: string
          examples:
            - Счёт успешно открыт
    ClientAccount:
      type: object
      description: Данные о счёте клиента
      properties:
        name:
          type: string
          examples:
            - Депозитный
        amount:
          type: string
          format: number
          examples:
            - 1234.45
      required:
        - name
        - amount
    ClientResponse:
      type: object
      description: Данные клиента
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/ClientAccount'
    AccountResponse:
      type: object
      description: Счёт доступный для открытия
      properties:
        name:
          type: string
          examples:
            - Акционный
        description:
          type: string
          examples:
            - Счёт для новых клиентов
        initAmount:
          type: number
          format: double
          examples:
            - 1000
        type:
          type: string
          enum:
            - common
            - promo
            - default
          description: >
            Типы счетов:
             * `common` - Стандартный счёт, рекомендуется открывать уже существующим клиентам
             * `promo` - Акционный счёт, рекомендуется отрывать новым клиентам
             * `default` - Счёт, который открывается по-умолчанию для новых клиентов, если сейчас не проходит ни каких акций
      required:
        - name
        - type
    ErrorResponse:
      type: object
      description: Формат непредвиденной ошибки
      properties:
        message:
          type: string
          examples:
            - Во время выполнения запроса сервер столкнулся с непредвиденной ситуацией
        type:
          type: string
          examples:
            - InternalServerError
        code:
          type: string
          examples:
            - 500
        traceId:
          type: string
          format: uuid
          examples:
            - 5f59e024-03c7-498d-9fc9-b8b15fd49c47
  parameters:
    telegramId:
      name: telegramId
      in: path
      description: Идентификатор пользователя в Telegram
      required: true
      schema:
        type: integer
        format: int64
        examples:
          - 356789

tags:
  - name: clients
    description: Операции с клиентами
