spring:
  application:
    name: gladskoy-telegram-bot
  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          middle-clients-service:
            url: http://localhost:8081/api
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %clr(%5level) [%15.15t] %clr(%-45.55logger{39}){cyan} : %m%n%wEx"
  level:
    ru.gpbitfactory.minibank.telegrambot:
      command: info
      handler: info
      restclient: debug
      service: info
    org:
      telegram:
        telegrambots: debug

server:
  port: 8080

telegram-bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  allow-commands-with-parameters: true
